name: NLobby
version: ${project.version}
main: com.notpatch.nLobby.NLobby
api-version: '1.21'

loader: com.notpatch.nLobby.LibraryLoader

dependencies:
  server:
    PlaceholderAPI:
      required: false
      load: BEFORE

